name: Run Auto-TVxml Script

on:
  schedule:
    - cron: '0 9 * * *'
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

    - name: Run Auto-TVxml Script
      run: python ${{ github.workspace }}/Auto-TVxml.py

    - name: Commit and push changes
      run: |
        git config --local user.email "lh654850695@gmail.com"
        git config --local user.name "lh654850695"
        git add tvxml.xml
        git status  # 添加调试信息
        git commit -m "Update tvxml.xml"
        git status  # 添加调试信息
        git log --oneline  # 添加调试信息
        git push
